spring:
  datasource:
    driver-class-name: mongodb.jdbc.MongoDriver
  data:
    mongodb:
      uri: mongodb://localhost:27017/testDb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    